apiVersion: v1
kind: Service
metadata:
  name: node-app-service  # Name of the service
spec:
  type: NodePort  # NodePort type for external access via a specific port
  selector:
    app: node-app  # This must match the label in your deployment
  ports:
    - protocol: TCP
      port: 80  # External port (you can access the app on <NodeIP>:<NodePort>)
      targetPort: 8080  # Port on the container (must match containerPort in deployment)
      nodePort: 30002  # Choose another port in the valid range
