const express=require('express')
const userConroller=require('../controller/usercontroler')
const addressController=require('../controller/addressController')
const cartController=require('../controller/cartController')
const Router=express.Router()
const {isuser}=require('../middlewere/userver')
const blockedUser=require('../middlewere/userblock')
const orderConroller=require('../controller/orderController')

Router.get('/login',userConroller.loginget)
Router.get('/',blockedUser,userConroller.home)

Router.post('/login',userConroller.logionverify)
Router.get('/signup',userConroller.signupget)
Router.post('/verifyotp',userConroller.verifyotp)
Router.post('/signup',userConroller.userRegister)
Router.post('/resendotp',userConroller.resendotp)
Router.get('/sendotp',userConroller.otppage)
Router.post('/register',userConroller.register)
Router.get('/shop',blockedUser,userConroller.shopPage)
Router.get('/singleProduct',isuser,blockedUser,userConroller.singleProduct)
Router.get('/logout',userConroller.logout)
Router.get('/productsearch',userConroller.prodeuctsearch)
Router.get('/price',userConroller.priceRange)
Router.get('/namesort',userConroller.nameSort)
Router.get('/pricesort',userConroller.priceSort)
Router.get('/parent',userConroller.Parent)

// addressController
Router.get('/account',addressController.account)
Router.get('/addaddress',addressController.addaddress)
Router.post('/addaddress',addressController.addaddress2)
Router.get('/myaddress',addressController.Myaddress)
Router.get('/editadd/:id',addressController.editAdd)
Router.put('/updateadd',addressController.updateAdd)
Router.get('/deleteAdd',addressController.deleteAdd)
Router.put('/updatePro',addressController.updatePro)
//cart
Router.get('/cart',cartController.Cart)
Router.post("/addtocart",cartController.addTocart)
Router.get('/cartbutton',cartController.cartbutton)
Router.get('/removecart',cartController.removeCart)
//checkout
Router.get('/checkout',cartController.checkOut1)
Router.get('/checkout2',cartController.checkOut2)
Router.get('/checkout3',cartController.checkOut3)
Router.post('/checkout4',cartController.checkOut4)
Router.get('/checkout5',cartController.checkOut5)
//orders
Router.get('/allorders',orderConroller.allOrder)
Router.get('/singleorders',orderConroller.singleOrder)
Router.get('/cancel',orderConroller.Cancel)
Router.post('/cancelall',orderConroller.Cancelall)
//whishlist
Router.get('/whishlist',userConroller.Whishlist)
module.exports=Router